### ISSUE TITLE
XMLParsedAsHTMLWarning when using leo-cli

### ISSUE THREAD

**Issue by davipbl** [joidegn/leo-cli#23]
I am getting this warning, how can I fix it?

`leo Zeitgrund
/home/davipbl/.local/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument 'features="xml"' into the BeautifulSoup constructor.
  warnings.warn(
English         German
reason of time  der Zeitgrund (die Zeitgründe)`

**Comment by joidegn** [comment]
Ah great. Thanks @mickeyl . If you want to make a PR I'll accept it.

**Comment by mickeyl** [comment]
Will do!
