### ISSUE TITLE
`XMLParsedAsHTMLWarning`

### ISSUE THREAD

**Issue by maxfrei750** [joidegn/leo-cli#25]
Thanks for the awesome tool! I receive a warning:

```
XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
```

I would have tried to fix it and make a PR, but I'm unsure if the warning should just be ignored or the response should actually be parsed as XML.

**Comment by mickeyl** [comment]
This has been fixed last year as per https://github.com/joidegn/leo-cli/commit/989cde93ea9f601a3346c03977c74d2c451fd742 ­– unfortunately @joidegn didn't cut a release since then.

**Comment by maxfrei750** [comment]
@mickeyl Thanks for letting me know! @joidegn, The last release has been a while and there have been many improvements. Would you consider a new release?

**Comment by joidegn** [comment]
Sorry about being slow here. Doing it today.

Thanks for your contributions!

**Comment by maxfrei750** [comment]
@joidegn It's free software, so no obligations for you to do anything. :smile: So, even more, thanks for taking the time! :+1:
