### ISSUE TITLE
No permission error

### ISSUE THREAD

**Issue by uloco** [joidegn/leo-cli#6]
Installation went fine, but when executing the commands from the terminal I get the following error:
`bash: /usr/local/bin/leo: Permission denied`
I am on Ubuntu 15.10.

I fixed this by changing the permissions: `sudo chmod ugo+x /usr/local/bin/leo`

**Comment by joidegn** [comment]
funky as I have this flag set already on my system after installation. thanks for reporting anyhow.

**Comment by joidegn** [comment]
I think this does not occur (at least anymore) so Im closing this.
