### ISSUE TITLE
You should mention that lxml is required

### ISSUE THREAD

**Issue by muellan** [joidegn/leo-cli#9]
Thanks for the great tool!

I also needed to install **lxml** in order to make it work.
Note that on Ubuntu you should use `apt` not `pip` to install lxml: `sudo apt-get install python-lxml`.

**Comment by joidegn** [comment]
You are right! Feel free to open a pull-request.

**Comment by garfieldnate** [comment]
I think this can be closed via dd7707e50989f70. You just have to do `pip install -r requirements.txt` now.
